Algoritmo "Meu_primeiro_algoritmo"
// Disciplina   : [Algoritmos e Lógica de programação]
// Professor   : Cleison Ferreira de Melo
// Descrição   : Exibe variável nota
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/04/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva ("Resultado:", nota)

Fimalgoritmo