Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Melo
// Descrição   : Estudo de tipos de dados
// Autor(a)    : Fernando Sousa
// Data atual  : 28/04/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro, notasdois: real, nome: caractere, passou: logico;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo